// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzadczzgyghnrshszyft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6YWRjenpneWdobnJzaHN6eWZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNzIxMjcsImV4cCI6MjA3NTk0ODEyN30.hC8AIu6wGjRF1oMsAIEHFbR8LU2RNCqreqOQFv8wzwA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});